# Generated by Django 5.0.10 on 2026-05-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_language',
            field=models.CharField(choices=[('en-in', 'English (India)'), ('te', 'Telugu'), ('hi', 'Hindi')], default='en-in', help_text="Default UI language for this broker's staff.", max_length=10, verbose_name='Default language'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en-in', 'English (India)'), ('te', 'Telugu'), ('hi', 'Hindi')], help_text='Overrides the tenant default. Blank = use tenant default.', max_length=10, verbose_name='Preferred UI language'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Business name'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(help_text='Used as subdomain: <slug>.goldloan.in', unique=True, verbose_name='Subdomain'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_tenant_owner',
            field=models.BooleanField(default=False, help_text='Tenant owners can manage their tenant settings & users.', verbose_name='Is tenant owner'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Null = platform super-admin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='iam.tenant', verbose_name='Tenant'),
        ),
    ]
