# Generated by Django 5.0.10 on 2026-05-19 18:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_tenant_default_language_user_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='max_ltv_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text='RBI cap is 75%. Apply on origination.', max_digits=5, verbose_name='Max LTV %'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('manager', 'Branch Manager'), ('cashier', 'Cashier'), ('appraiser', 'Appraiser'), ('auditor', 'Auditor (read-only)')], default='owner', help_text='Determines what this user can do inside the tenant.', max_length=20, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Branch name')),
                ('code', models.CharField(help_text='Short code shown on receipts, e.g. HYD1', max_length=20, verbose_name='Code')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('license_no', models.CharField(blank=True, help_text='Overrides tenant license if set.', max_length=100, verbose_name='License #')),
                ('gst_no', models.CharField(blank=True, help_text='Overrides tenant GST if set.', max_length=20, verbose_name='GST #')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_primary', models.BooleanField(default=False, help_text='Used as the default when no branch is selected.', verbose_name='Primary branch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['tenant_id', '-is_primary', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Primary branch (used as default in forms).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='iam.branch'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_branch_code_per_tenant'),
        ),
    ]
