# Generated by Django 5.0.10 on 2026-06-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_tenant_max_ltv_pct_user_role_branch_user_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='accent_color',
            field=models.CharField(default='#f59e0b', help_text='Secondary/highlight hex colour, e.g. #f59e0b.', max_length=7, verbose_name='Accent colour'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Shown in the admin sidebar, emails and auction notices. PNG/SVG with transparent background works best.', null=True, upload_to='tenant/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#c46616', help_text='Brand colour as a hex code, e.g. #c46616. Themes the admin UI, emails and auction notices.', max_length=7, verbose_name='Primary colour'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tagline',
            field=models.CharField(blank=True, help_text='Sub-heading under the business name, e.g. "Gold Finance". Leave blank to hide.', max_length=120, verbose_name='Tagline'),
        ),
    ]
