# Generated by Django 5.0.10 on 2026-06-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_tenant_accent_color_tenant_logo_tenant_primary_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_rate_type',
            field=models.CharField(choices=[('annual', 'Per Annum (% p.a.)'), ('monthly', 'Per Month (% p.m.)')], default='monthly', help_text='Pre-selected interest rate type when staff create a new loan. Values match Loan.RateType.', max_length=10, verbose_name='Default interest rate type'),
        ),
    ]
