# Generated by Django 5.0.10 on 2026-05-19 18:35

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0003_tenant_max_ltv_pct_user_role_branch_user_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('purity_carat', models.DecimalField(decimal_places=2, default=Decimal('22.00'), help_text='Most pawn loans value at 22 ct.', max_digits=4, verbose_name='Purity (carat)')),
                ('rate_per_gram_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('rate_per_gram', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, verbose_name='Rate per gram')),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('ibja', 'IBJA feed'), ('other', 'Other')], default='manual', max_length=10, verbose_name='Source')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Gold rate',
                'verbose_name_plural': 'Gold rates',
                'ordering': ['-rate_date', '-purity_carat'],
            },
        ),
        migrations.AddConstraint(
            model_name='goldrate',
            constraint=models.UniqueConstraint(fields=('tenant', 'rate_date', 'purity_carat'), name='uniq_rate_per_tenant_date_purity'),
        ),
    ]
