# Generated by Django 5.0.10 on 2026-05-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_language',
            field=models.CharField(choices=[('en-in', 'English (India)'), ('te', 'Telugu'), ('hi', 'Hindi')], default='en-in', help_text='Used for SMS / WhatsApp reminders sent to this customer.', max_length=10, verbose_name='Preferred language'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
