# Generated by Django 5.0.10 on 2026-05-19 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_preferred_language_alter_customer_notes'),
        ('iam', '0003_tenant_max_ltv_pct_user_role_branch_user_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Home branch for this customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='iam.branch'),
        ),
    ]
