# Generated by Django 5.0.10 on 2026-06-01 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='aadhaar_last4',
        ),
        migrations.AddField(
            model_name='customer',
            name='aadhaar',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar number', max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar must be exactly 12 digits.')]),
        ),
    ]
