# Generated by Django 5.0.10 on 2026-05-19 21:45

import apps.signup.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0003_tenant_max_ltv_pct_user_role_branch_user_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='Business name')),
                ('slug', models.SlugField(verbose_name='Subdomain')),
                ('owner_username', models.CharField(max_length=150, verbose_name='Owner username')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Owner email')),
                ('owner_phone', models.CharField(max_length=20, verbose_name='Owner phone')),
                ('license_no', models.CharField(blank=True, max_length=100, verbose_name='License #')),
                ('gst_no', models.CharField(blank=True, max_length=20, verbose_name='GST #')),
                ('plan', models.CharField(default='starter', max_length=20, verbose_name='Plan')),
                ('token', models.CharField(db_index=True, default=apps.signup.models._gen_token, max_length=64, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(default=apps.signup.models._default_expiry, verbose_name='Expires at')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signup_request', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Signup request',
                'verbose_name_plural': 'Signup requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
