# Generated by Django 5.0.10 on 2026-05-19 21:52

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0003_tenant_max_ltv_pct_user_role_branch_user_branch_and_more'),
        ('loans', '0005_alter_golditem_gross_weight_g_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('eligible', 'Eligible for auction'), ('notice1_sent', 'Notice 1 sent'), ('notice2_sent', 'Notice 2 sent (final)'), ('scheduled', 'Scheduled'), ('sold', 'Sold (awaiting posting)'), ('posted', 'Posted (settled)'), ('cancelled', 'Cancelled (borrower settled)')], db_index=True, default='eligible', max_length=20, verbose_name='Status')),
                ('eligible_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eligible at')),
                ('notice1_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Notice 1 sent at')),
                ('notice2_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Notice 2 sent at')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Auction scheduled for')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Auction location')),
                ('bidder_name', models.CharField(blank=True, max_length=200, verbose_name='Winning bidder')),
                ('bidder_phone', models.CharField(blank=True, max_length=20, verbose_name='Bidder phone')),
                ('bidder_id_proof', models.CharField(blank=True, max_length=80, verbose_name='Bidder ID proof')),
                ('sold_amount_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3, null=True)),
                ('sold_amount', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Sold for')),
                ('total_dues_at_sale_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3, null=True)),
                ('total_dues_at_sale', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total dues at sale')),
                ('surplus_amount_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('surplus_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Surplus refundable')),
                ('shortfall_amount_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('shortfall_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Shortfall')),
                ('surplus_refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='Surplus refunded at')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='auction', to='loans.loan')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'ordering': ['-eligible_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice_no', models.PositiveSmallIntegerField(verbose_name='Notice #')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sent at')),
                ('channels', models.JSONField(blank=True, default=list, help_text='List of channels used, e.g. ["email","whatsapp","registered_post"]', verbose_name='Channels')),
                ('delivery_ref', models.CharField(blank=True, help_text='Email message id / Reg.Post tracking / etc.', max_length=200, verbose_name='Delivery reference')),
                ('pdf_path', models.FileField(blank=True, null=True, upload_to='auctions/notices/', verbose_name='PDF copy')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='auctions.auction')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Auction notice',
                'verbose_name_plural': 'Auction notices',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='auctionnotice',
            constraint=models.UniqueConstraint(fields=('auction', 'notice_no'), name='uniq_notice_per_auction'),
        ),
    ]
