# Generated by Django 5.0.10 on 2026-05-19 16:51

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_no', models.CharField(db_index=True, max_length=30)),
                ('principal_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('principal', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('interest_rate_pct', models.DecimalField(decimal_places=3, help_text='Annual interest rate, e.g. 24.000 = 24% p.a.', max_digits=6)),
                ('tenure_months', models.PositiveSmallIntegerField(default=12)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('maturity_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('overdue', 'Overdue'), ('closed', 'Closed'), ('auctioned', 'Auctioned')], default='active', max_length=20)),
                ('packet_no', models.CharField(blank=True, help_text='Physical packet / locker tag', max_length=50)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='customers.customer')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='iam.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='e.g. "2 gold bangles"', max_length=200)),
                ('gross_weight_g', models.DecimalField(decimal_places=3, max_digits=8)),
                ('stone_weight_g', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8)),
                ('net_weight_g', models.DecimalField(decimal_places=3, max_digits=8)),
                ('purity_carat', models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=4)),
                ('rate_per_gram_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3, null=True)),
                ('rate_per_gram', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='loans/items/')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='iam.tenant')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loans.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('principal_paid_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('principal_paid', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('interest_paid_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('interest_paid', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer')], default='cash', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='UPI ref / Bank txn id', max_length=100)),
                ('receipt_no', models.CharField(blank=True, max_length=30)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='iam.tenant')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(fields=('tenant', 'loan_no'), name='uniq_loan_no_per_tenant'),
        ),
    ]
