# Generated by Django 5.0.10 on 2026-05-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='rate_type',
            field=models.CharField(choices=[('annual', 'Per Annum (% p.a.)'), ('monthly', 'Per Month (% p.m.)')], default='annual', help_text='Is the rate below annual or monthly?', max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate_pct',
            field=models.DecimalField(decimal_places=3, help_text='Number only, e.g. 24.000. Combined with "Rate type" on the left: 24 % p.a. or 2 % p.m.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='loan',
            name='maturity_date',
            field=models.DateField(blank=True, help_text='Auto-calculated as start_date + tenure_months.'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='tenure_months',
            field=models.PositiveSmallIntegerField(default=12, help_text='Loan duration in calendar months (default 12).'),
        ),
    ]
