# Generated by Django 5.0.10 on 2026-05-19 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_rate_type_alter_loan_interest_rate_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='renewed_to',
            field=models.ForeignKey(blank=True, help_text='If this loan was renewed/topped-up, points to the new loan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_from', to='loans.loan'),
        ),
    ]
