# Generated by Django 5.0.10 on 2026-05-19 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_tenant_max_ltv_pct_user_role_branch_user_branch_and_more'),
        ('loans', '0003_loan_closed_at_loan_renewed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='branch',
            field=models.ForeignKey(blank=True, help_text="Defaults to the tenant's primary branch if blank.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='iam.branch'),
        ),
    ]
