# Generated by Django 5.0.10 on 2026-05-19 19:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golditem',
            name='gross_weight_g',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Gross weight (g)'),
        ),
        migrations.AlterField(
            model_name='golditem',
            name='net_weight_g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Leave blank to auto-compute as Gross − Stone.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Net weight (g)'),
        ),
        migrations.AlterField(
            model_name='golditem',
            name='purity_carat',
            field=models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Purity (ct)'),
        ),
        migrations.AlterField(
            model_name='golditem',
            name='stone_weight_g',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Stone weight (g)'),
        ),
    ]
