# Generated by Django 5.0.10 on 2026-06-22 11:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_alter_golditem_gross_weight_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golditem',
            name='net_weight_g',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Leave blank to auto-compute as Gross − Wastage.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Net weight (g)'),
        ),
        migrations.AlterField(
            model_name='golditem',
            name='stone_weight_g',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))], verbose_name='Wastage (g)'),
        ),
    ]
