# Generated by Django 5.0.10 on 2026-06-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0005_tenant_default_rate_type'),
        ('loans', '0007_backfill_repayment_receipt_no'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.UniqueConstraint(fields=('tenant', 'receipt_no'), name='uniq_receipt_no_per_tenant'),
        ),
    ]
