# Generated by Django 5.0.10 on 2026-06-25 12:13

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_repayment_uniq_receipt_no_per_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='interest_waived',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), help_text='Interest forgiven as a goodwill gesture. NOT cash — it reduces what the customer owes but is excluded from the cash receipt total.', max_digits=12),
        ),
        migrations.AddField(
            model_name='repayment',
            name='interest_waived_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3),
        ),
    ]
