# Generated by Django 5.0.10 on 2026-05-19 21:34

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0003_tenant_max_ltv_pct_user_role_branch_user_branch_and_more'),
        ('loans', '0005_alter_golditem_gross_weight_g_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('close_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Close date')),
                ('opening_balance_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('opening_balance', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Opening balance')),
                ('computed_in_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('computed_in', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Computed in')),
                ('computed_out_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('computed_out', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Computed out')),
                ('closing_balance_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('closing_balance', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Closing balance (system)')),
                ('physical_count_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('physical_count', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Physical count')),
                ('variance_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('variance', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Variance')),
                ('denomination_json', models.JSONField(blank=True, default=dict, verbose_name='Denominations')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_closes', to='iam.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Day close',
                'verbose_name_plural': 'Day closes',
                'ordering': ['-close_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('txn_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='Date')),
                ('kind', models.CharField(choices=[('opening', 'Opening balance'), ('disburse_out', 'Loan disbursement (out)'), ('repayment_in', 'Loan repayment (in)'), ('capital_in', 'Capital injection (in)'), ('drawal_out', 'Owner drawal (out)'), ('expense_out', 'Expense (out)'), ('bank_deposit', 'Bank deposit (out of cash)'), ('bank_withdrawal', 'Bank withdrawal (into cash)'), ('adjustment', 'Adjustment')], db_index=True, max_length=20, verbose_name='Kind')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Amount')),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=10, verbose_name='Mode')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='iam.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='loans.loan')),
                ('source_repayment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='loans.repayment')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='iam.tenant')),
            ],
            options={
                'verbose_name': 'Cash transaction',
                'verbose_name_plural': 'Cash transactions',
                'ordering': ['-txn_date', '-id'],
                'indexes': [models.Index(fields=['tenant', 'txn_date'], name='cashbook_ca_tenant__0f5b3d_idx'), models.Index(fields=['tenant', 'branch', 'txn_date'], name='cashbook_ca_tenant__23fc8b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dayclose',
            constraint=models.UniqueConstraint(fields=('tenant', 'branch', 'close_date'), name='uniq_dayclose_per_tenant_branch_date'),
        ),
    ]
