# Generated by Django 5.0.10 on 2026-06-22 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbook', '0001_initial'),
        ('loans', '0005_alter_golditem_gross_weight_g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashtransaction',
            name='source_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='loans.loan'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='source_repayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_transactions', to='loans.repayment'),
        ),
    ]
