# Generated by Django 5.0.10 on 2026-05-19 16:51

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_month', models.DateField(help_text='First day of the month this reminder covers')),
                ('interest_due_currency', djmoney.models.fields.CurrencyField(choices=[('INR', 'Indian Rupee')], default='INR', editable=False, max_length=3)),
                ('interest_due', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('log', 'Log only')], default='whatsapp', max_length=10)),
                ('to_phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='loans.loan')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='iam.tenant')),
            ],
            options={
                'ordering': ['-period_month', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='interestreminder',
            constraint=models.UniqueConstraint(fields=('loan', 'period_month', 'channel'), name='uniq_reminder_per_loan_month_channel'),
        ),
    ]
